[package]
name = "genet-sdk"
description = "genet SDK"
license = "MIT"
version = "0.4.0"
authors = ["Ron Hashimoto <mail@h2so5.net>"]

[dependencies]
byteorder = "1"
lazy_static = "1"
genet-abi = "0.4.0"
