[package]
name = "genet-abi"
description = "genet ABI definitions"
license = "MIT"
version = "0.4.0"
authors = ["Ron Hashimoto <mail@h2so5.net>"]

[dependencies]
libc = "0.2"
lazy_static = "1"
fnv = "1"